name: Cypress BDD Tests

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
            build: npx cypress info
            browser: chrome
            record: true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
            name: cucumber-report.html
            path: .