name: Cypress BDD Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npx cypress info
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Move cucumber report
        run: |
          mkdir -p cypress/report
          mv cucumber-report.html cypress/report/  

      - uses: actions/upload-artifact@v3
        if: success()  
        with:
          name: cucumber-report
          path: cypress/report